#!/usr/bin/env python3

from sys import argv
from math import gcd
from sympy import isprime

def pollards_rho(n):
    x = 2
    y = 2
    d = 1

    f = lambda x: (x**2 + 1) % n

    while d == 1:
        x = f(x)
        y = f(f(y))
        d = gcd(abs(x - y), n)

    return d

def factorize_number(n):
    factors = []

    while not isprime(n):
        factor = pollards_rho(n)
        factors.append(factor)
        n //= factor

    factors.append(n)
    return factors

if __name__ == "__main__":
    if len(argv) != 2:
        print("Usage: factors <file>")
        exit(1)

    filename = argv[1]
    with open(filename, "r", encoding="utf-8") as file:
        number = int(file.readline().strip())

    factors = factorize_number(number)
    print(f"{number}={'*'.join(map(str, factors))}")
